### PR TITLE
Use `const fn`s to avoid any need for a static lock types

### PR DESCRIPTION
**Pull request by Ericson2314**
Now there's no more temptation to publicize the fields!

### CODE REVIEW

**Comment by mvdnes** [comment]
The build seems to fail on the new syntax. However, I think because of the nature of the library, I am considering to make it nightly-only. It will mostly be used by libcore users anyway.

Can you ensure this at least builds on nightly?

**Comment by Ericson2314** [comment]
I manually tested on nightly, but I thought I had it written so without the "no_std" feature, it should build on a stable compiler.

**Comment by mvdnes** [comment]
I have published this changes in version 0.3.0 of the crate. I will not be activly monitoring the breaking changes in nightly, so if anything comes up don't hessitate to issue a PR or create an issue.

Thanks for the contribution!

**Comment by Ericson2314** [comment]
Ah, just remembered that code behind a cfg still needs to tokenize no matter what, hence why it failed to build on stable. Thanks for accepting!

**Pull request merged**
