### PR TITLE
Add a spinning-based RwLock

### PR DESCRIPTION
**Pull request by Ericson2314**
Not sure what you want to do regarding names, but mimicking `std::sync` I suppose has some benefits.

### CODE REVIEW

**Comment by Ericson2314** [comment]
Ah, missed the tests in the README. I'll push a fix in a moment.

**Comment by mvdnes** [comment]
Looks great!

One last addition would be that a reader would block/return None if there are too many readers. Granted, that only happens at 2^31-1 readers, but I would like to keep rusts safety in mind.

Also some (doc?)tests would be nice, but I will also merge it without them.

**Comment by Ericson2314** [comment]
Glad you like it!

Mmm, since the number of potential readers is half the address space, and the rw lock is not recursive, that means each thread could take no more than 2 bytes. I put in a `debug_assert` because errors in the library are certainly possible, but I even with tons of swap space I do not think it is possible to hit that number of readers.

I'd be happy to add doc tests.

**Comment by mvdnes** [comment]
Hmm you are right. That would be very unlikely indeed. Especially since this holds for each size of usize.

Looking forward to the tests!

**Comment by Ericson2314** [comment]
Thanks for merging! And sorry I haven't added the doc-tests yet, been busy. I'll try to get to that soon.

**Comment by mvdnes** [comment]
:+1:

**Pull request merged**
